"""Trilingual, route-aware offline manual for every TPS workspace."""
from __future__ import annotations

from html import escape


PAGES = (
    (0, "Dashboard",
     "Daily command centre showing journal activity, open paper trades and key totals. Refresh reads saved records; it does not fetch or place broker orders.",
     "Aaj ki journal activity, open paper trades aur main totals ka command centre. Refresh saved records ko padhta hai; broker order fetch ya place nahi karta.",
     "आज की जर्नल गतिविधि, खुले पेपर ट्रेड और मुख्य योग दिखाने वाला कमांड सेंटर। Refresh केवल सुरक्षित रिकॉर्ड पढ़ता है; ब्रोकर ऑर्डर नहीं लगाता।",
     "Review daily status, open-paper risk, P&L summaries and shortcuts before starting research.",
     "Research se pehle daily status, open-paper risk, P&L summary aur shortcuts check karein.",
     "रिसर्च शुरू करने से पहले दैनिक स्थिति, खुले पेपर जोखिम, P&L सारांश और शॉर्टकट देखें।"),
    (1, "Market Snapshot",
     "Live overview for NIFTY, BANKNIFTY and SENSEX using the selected timeframe. Stable support/resistance zones come from clustered completed-candle swing reactions rather than the latest candle alone.",
     "Selected timeframe par NIFTY, BANKNIFTY aur SENSEX ka live overview. Support/resistance latest candle se nahi, repeated completed-candle swing reactions ke stable zone se banta hai.",
     "चुने हुए टाइमफ्रेम पर NIFTY, BANKNIFTY और SENSEX का लाइव अवलोकन। सपोर्ट/रेज़िस्टेंस नवीनतम कैंडल से नहीं, बार-बार बने पूर्ण-कैंडल स्विंग के स्थिर क्षेत्र से बनते हैं।",
     "Choose index and timeframe, run analysis, or save 5m+15m snapshots. A valid zone is retained until price invalidates it or a replacement zone repeats across three analyses. Fast index switching discards late results from the previously selected index.",
     "Index/timeframe select karein. Valid zone tab tak hold hota hai jab tak price use invalidate na kare ya naya zone 3 analysis me repeat na ho. Fast switching par purane index ka late result discard hota hai.",
     "इंडेक्स/टाइमफ्रेम चुनें। वैध क्षेत्र तब तक स्थिर रहता है जब तक मूल्य उसे अमान्य न करे या नया क्षेत्र तीन विश्लेषण में दोहराया न जाए। तेज़ स्विचिंग में पिछले इंडेक्स का देर से आया परिणाम हट जाता है।"),
    (2, "Options Workspace",
     "Main index-option planning workspace. It loads expiry, type, strike, lots and live contract/OI data, evaluates TPS confirmations, creates paper review plans and includes an opt-in 20-point scalp paper-validation audit.",
     "Index-option planning ka main workspace. Expiry, type, strike, lots aur live contract/OI data ke saath TPS confirmations check karta hai. Opt-in 20-point scalp mode READY/WATCH/NO TRADE ko audit karta hai; order place nahi karta. Evidence TRUE, FALSE ya UNKNOWN ho sakta hai; UNKNOWN ko pass nahi maana jata.",
     "इंडेक्स-ऑप्शन योजना का मुख्य कार्यक्षेत्र। यह एक्सपायरी, प्रकार, स्ट्राइक, लॉट और लाइव कॉन्ट्रैक्ट/OI डेटा लेकर TPS पुष्टि जाँचता, पेपर प्लान बनाता और पेपर एग्जिट मॉनिटर करता है।",
     "Use Load Expiries, Analyze Contract, Analyze OI/PCR, score threshold (0–100), Create Review Plan, Capture Paper Trade and Auto Paper toggle. News/event and core safety blockers remain independent of score.",
     "Load Expiries, Analyze Contract, Analyze OI/PCR, 0–100 score, Create Review Plan, Capture Paper Trade aur Auto Paper toggle use karein. News/event aur core safety blockers score se alag rahte hain.",
     "Load Expiries, Analyze Contract, Analyze OI/PCR, 0–100 स्कोर, Create Review Plan, Capture Paper Trade और Auto Paper विकल्प उपयोग करें। समाचार/इवेंट और मुख्य सुरक्षा अवरोध स्कोर से स्वतंत्र रहते हैं।"),
    (3, "Chart Capture",
     "Builds a standardized 5-minute setup from broker candles or a chart screenshot. It records OHLC, EMA 5/20/50, VWAP, RSI, ATR, SuperTrend and Volume EMA 20.",
     "Broker candles ya screenshot se standardized 5-minute setup banata hai. OHLC, EMA 5/20/50, VWAP, RSI, ATR, SuperTrend aur Volume EMA 20 record karta hai.",
     "ब्रोकर कैंडल या स्क्रीनशॉट से मानकीकृत 5-मिनट सेटअप बनाता है। OHLC, EMA 5/20/50, VWAP, RSI, ATR, SuperTrend और Volume EMA 20 दर्ज करता है।",
     "Choose Screenshot for local OCR or Capture Current-Month Future for live values; verified values are evaluated directly and forwarded to Options Workspace.",
     "Local OCR ke liye Screenshot ya live values ke liye Current-Month Future chunein; verified values seedha evaluate hokar Options Workspace me jayengi.",
     "स्थानीय OCR के लिए Screenshot या लाइव मानों के लिए Current-Month Future चुनें; सत्यापित मान सीधे जाँचकर Options Workspace में भेजे जाते हैं।"),
    (4, "Trade Journal",
     "Permanent record of planned and completed trades, including entry, stop, targets, actual exit, outcome, screenshots, mistakes and review notes.",
     "Planned aur completed trades ka permanent record—entry, stop, target, actual exit, outcome, screenshot, mistake aur review notes.",
     "योजनाबद्ध और पूर्ण ट्रेड का स्थायी रिकॉर्ड—एंट्री, स्टॉप, लक्ष्य, वास्तविक एग्जिट, परिणाम, स्क्रीनशॉट, गलती और समीक्षा नोट।",
     "Add/edit a plan, open or close a paper trade, record target/stop outcome and post-mortem. Journal facts drive Dashboard and Reports, so do not overwrite actual outcomes.",
     "Plan add/edit, paper trade open/close, target/stop outcome aur post-mortem record karein. Journal data Dashboard/Reports chalata hai, isliye actual result overwrite na karein.",
     "प्लान जोड़ें/संपादित करें, पेपर ट्रेड खोलें/बंद करें, लक्ष्य/स्टॉप परिणाम और पोस्ट-मॉर्टम दर्ज करें। वास्तविक परिणाम न बदलें क्योंकि यही Dashboard/Reports का स्रोत है।"),
    (5, "Checklist",
     "Manual discipline gate used before any trade: trend, entry timing, volume, level safety, risk and psychology confirmations.",
     "Trade se pehle manual discipline gate: trend, entry timing, volume, level safety, risk aur psychology confirmations.",
     "ट्रेड से पहले मैनुअल अनुशासन जाँच: ट्रेंड, एंट्री समय, वॉल्यूम, स्तर सुरक्षा, जोखिम और मनोविज्ञान पुष्टि।",
     "Tick only conditions personally verified from current data. A completed checklist documents discipline; it does not convert a weak setup into a valid signal.",
     "Sirf current data se khud verified condition tick karein. Checklist discipline record karti hai; weak setup ko valid signal nahi banati.",
     "केवल वर्तमान डेटा से स्वयं जाँची शर्त टिक करें। चेकलिस्ट अनुशासन दर्ज करती है; कमजोर सेटअप को वैध संकेत नहीं बनाती।"),
    (7, "Risk Control Center",
     "Checks whether a proposed option trade fits account capital, per-trade risk, daily loss capacity and maximum-trade limits.",
     "Proposed option trade capital, per-trade risk, daily loss capacity aur maximum-trade limit me fit hai ya nahi check karta hai.",
     "प्रस्तावित ऑप्शन ट्रेड पूँजी, प्रति-ट्रेड जोखिम, दैनिक हानि क्षमता और अधिकतम ट्रेड सीमा में है या नहीं जाँचता है।",
     "Select NIFTY/BANKNIFTY/SENSEX, enter premium, stop, target and planned lots. Quantity uses configured exchange lot size; Analyze shows rupee risk, R:R and PASS/BLOCK result.",
     "Index select karke premium, stop, target aur lots bharein. Quantity predefined lot size se; Analyze rupee risk, R:R aur PASS/BLOCK dikhata hai.",
     "इंडेक्स चुनकर प्रीमियम, स्टॉप, लक्ष्य और लॉट भरें। मात्रा निर्धारित लॉट आकार से निकलती है; Analyze रुपये का जोखिम, R:R और PASS/BLOCK दिखाता है।"),
    (8, "Reports",
     "Performance summaries plus an Excel Report Center for Trade Journal, attempts, notifications, opportunities, snapshots, PCR/OI, gap forecasts, trend memory, post-market and AI review records.",
     "Performance summary ke saath Excel Report Center: ek din, custom date period ya all available data ko selected report ya multi-sheet workbook me export karein.",
     "सुरक्षित जर्नल रिकॉर्ड से जीत, हानि, P&L, अनुशासन और समीक्षा प्रवृत्ति का सारांश।",
     "Refresh after journal updates. Choose From/To for one day or a period, or All Available Dates; select one report or All TPS Reports before exporting XLSX.",
     "Journal update ke baad Refresh karein. From/To se ek din ya period, ya All Available Dates choose karke selected report/all reports XLSX export karein.",
     "जर्नल अपडेट के बाद Refresh/फ़िल्टर करें। छूटा या गलत बंद ट्रेड रिपोर्ट योग को अधूरा करेगा।"),
    (9, "Settings",
     "Controls persistent risk limits, exchange session timing, themes, automation safety, notifications, calendar feed and encrypted broker credentials.",
     "Persistent risk limits, market timing, themes, automation safety, notifications, calendar feed aur encrypted broker credentials control karta hai.",
     "स्थायी जोखिम सीमा, बाज़ार समय, थीम, ऑटोमेशन सुरक्षा, नोटिफिकेशन, कैलेंडर फ़ीड और एन्क्रिप्टेड ब्रोकर क्रेडेंशियल नियंत्रित करता है।",
     "Set Pre-open, Regular Trading Start and Market Close only after an official timing change, then Save Settings. Early Watch is an optional near-qualified completed-candle study alert—not entry approval—and final strategy/safety checks still apply. Never share API keys, PINs, TOTP secrets or tokens.",
     "Official timing change par hi Pre-open, Trading Start aur Market Close set karke Save Settings karein. Early Watch near-qualified completed candle ka optional study alert hai, entry approval nahi; final strategy/safety checks phir bhi zaroori hain.",
     "केवल आधिकारिक समय बदलाव पर Pre-open, Trading Start और Market Close सेट करके Save Settings करें। Early Watch लगभग योग्य पूर्ण कैंडल का वैकल्पिक अध्ययन अलर्ट है, एंट्री स्वीकृति नहीं; अंतिम रणनीति/सुरक्षा जाँच फिर भी लागू रहती है।"),
    (10, "Backtesting",
     "Replays TPS rules on historical completed candles to estimate behaviour before live paper validation.",
     "Live paper validation se pehle historical completed candles par TPS rules replay karke behaviour estimate karta hai.",
     "लाइव पेपर सत्यापन से पहले ऐतिहासिक पूर्ण कैंडल पर TPS नियम चलाकर व्यवहार का अनुमान करता है।",
     "Choose symbol, timeframe/history and run the test; inspect trades, win/loss and drawdown. Results exclude perfect live fills and do not prove future profitability.",
     "Symbol/timeframe/history choose karke test chalayein; trades, win/loss, drawdown dekhein. Result future profit prove nahi karta.",
     "सिंबल/टाइमफ्रेम/इतिहास चुनकर परीक्षण चलाएँ; ट्रेड, जीत/हानि, ड्रॉडाउन देखें। परिणाम भविष्य का लाभ सिद्ध नहीं करता।"),
    (11, "Post-Market Report",
     "Raw after-market review of saved snapshots, candle evidence and trade outcomes for the chosen date.",
     "Selected date ke saved snapshot, candle evidence aur trade outcome ka raw after-market review.",
     "चुनी तारीख के सुरक्षित स्नैपशॉट, कैंडल प्रमाण और ट्रेड परिणाम की कच्ची बाजार-बाद समीक्षा।",
     "Select a date and generate/refresh the report. Use it as evidence for diagnosis, not as a rewritten trading story.",
     "Date select karke report generate/refresh karein. Diagnosis ke evidence ke roop me use karein, story badalne ke liye nahi.",
     "तारीख चुनकर रिपोर्ट बनाएँ/रीफ़्रेश करें। इसे निदान प्रमाण की तरह उपयोग करें, कहानी बदलने के लिए नहीं।"),
    (12, "Candle Replay",
     "Candle-by-candle training that hides future information and lets you review how TPS would react at each point.",
     "Future information hide karke candle-by-candle training; har point par TPS reaction review kar sakte hain.",
     "भविष्य की जानकारी छिपाकर कैंडल-दर-कैंडल प्रशिक्षण; प्रत्येक बिंदु पर TPS प्रतिक्रिया की समीक्षा।",
     "Load history, step forward one candle at a time and record the decision before revealing the next candle. Avoid jumping ahead when testing discipline.",
     "History load karke ek-ek candle aage badhein aur next reveal se pehle decision note karein.",
     "इतिहास लोड कर एक-एक कैंडल आगे बढ़ें और अगली कैंडल दिखने से पहले निर्णय लिखें।"),
    (13, "Equity Research",
     "Searchable NSE cash-equity research with historical candles, TPS score and personal watchlist.",
     "Searchable NSE cash-equity research, historical candles, TPS score aur personal watchlist.",
     "खोज योग्य NSE कैश-इक्विटी रिसर्च, ऐतिहासिक कैंडल, TPS स्कोर और व्यक्तिगत वॉचलिस्ट।",
     "Load NSE shares, type symbol/company to filter, choose timeframe/history, Analyze, then add/remove watchlist. It is long-only research and places no order.",
     "NSE shares load, type karke filter, timeframe/history choose, Analyze aur watchlist add/remove karein. Ye long-only research hai.",
     "NSE शेयर लोड करें, टाइप कर फ़िल्टर करें, टाइमफ्रेम/इतिहास चुनें, Analyze करें और वॉचलिस्ट जोड़ें/हटाएँ। यह केवल लॉन्ग रिसर्च है।"),
    (14, "Auto Attempt Report",
     "Permanent audit of every completed 5-minute automatic paper evaluation, including captures, rejections, skips and data errors.",
     "Har completed 5-minute auto paper evaluation ka permanent audit—capture, rejection, skip aur data error.",
     "हर पूर्ण 5-मिनट ऑटो पेपर मूल्यांकन का स्थायी ऑडिट—कैप्चर, अस्वीकृति, स्किप और डेटा त्रुटि।",
     "Switch Today/All, select a row for full OHLC/indicator/OI reasons, or export CSV. DATA GAP means evidence incomplete, SAFETY BLOCK means a protected risk lock, STRATEGY REJECT means rules failed, CANDIDATE means review-worthy and CAPTURED means paper capture.",
     "Today/All choose, row select karke full reason dekhein ya CSV export karein. SKIPPED aur NO TRADE alag states hain.",
     "Today/All चुनें, पंक्ति चुनकर पूरा कारण देखें या CSV निर्यात करें। SKIPPED और NO TRADE अलग स्थितियाँ हैं।"),
    (15, "About",
     "Product identity, purpose, contributors, version and read-only/paper-trading safety scope.",
     "Product identity, purpose, contributors, version aur read-only/paper safety scope.",
     "उत्पाद पहचान, उद्देश्य, योगदानकर्ता, संस्करण और read-only/पेपर सुरक्षा सीमा।",
     "Read this page to confirm what TPS can and cannot do. It is not financial advice and does not promise returns.",
     "TPS kya kar sakta aur kya nahi, yahan verify karein. Ye financial advice ya return promise nahi hai.",
     "TPS क्या कर सकता और क्या नहीं, यहाँ जाँचें। यह वित्तीय सलाह या रिटर्न का वादा नहीं है।"),
    (16, "Help",
     "This offline trilingual manual and dated release-note centre.",
     "Ye offline trilingual manual aur dated release-note centre hai.",
     "यह ऑफ़लाइन त्रिभाषी मैनुअल और दिनांकित रिलीज़-नोट केंद्र है।",
     "Use language tabs, table-of-contents links and Open Page links. Release Notes show completed reviewed changes—not unfinished ideas.",
     "Language tab, contents aur Open Page link use karein. Release Notes sirf completed reviewed changes dikhate hain.",
     "भाषा टैब, विषय-सूची और Open Page लिंक उपयोग करें। Release Notes केवल पूर्ण समीक्षा किए बदलाव दिखाते हैं।"),
    (17, "Next-Day Bias",
     "After-close research combining Spot/Future chart context and closing option-chain evidence for the next session.",
     "Market close ke baad Spot/Future chart aur closing option-chain evidence se next-session bias research.",
     "बाजार बंद होने के बाद स्पॉट/फ्यूचर चार्ट और क्लोज़िंग ऑप्शन-चेन प्रमाण से अगले सत्र का बायस रिसर्च।",
     "Select NIFTY/BANKNIFTY/SENSEX and load broker data or supporting snapshots where unavailable. Output is bullish/bearish/range bias with levels—not a guaranteed gap forecast.",
     "Index select karke broker data/snapshot load karein. Output bias aur levels hain, guaranteed gap forecast nahi.",
     "इंडेक्स चुनकर ब्रोकर डेटा/स्नैपशॉट लें। परिणाम बायस और स्तर हैं, निश्चित गैप पूर्वानुमान नहीं।"),
    (18, "Smart Money Lab",
     "Price-action research for swing structure, liquidity sweeps, BOS, CHOCH, order blocks, FVG and supply/demand context.",
     "Swing structure, liquidity sweep, BOS, CHOCH, order block, FVG aur supply/demand ka price-action research.",
     "स्विंग संरचना, लिक्विडिटी स्वीप, BOS, CHOCH, ऑर्डर ब्लॉक, FVG और सप्लाई/डिमांड का प्राइस-एक्शन रिसर्च।",
     "Choose symbol/timeframe and analyze completed candles. Events are algorithmic estimates and must agree with trend, volume and levels before use.",
     "Symbol/timeframe choose karke completed candles analyze karein. Event estimates ko trend, volume aur levels se confirm karein.",
     "सिंबल/टाइमफ्रेम चुनकर पूर्ण कैंडल विश्लेषण करें। अनुमानित घटनाओं को ट्रेंड, वॉल्यूम और स्तर से पुष्टि करें।"),
    (19, "CAS Analysis",
     "After-close F&O-stock comparison of the 3:00–3:15 reference VWAP, final cash close and front-month futures close.",
     "Market close ke baad F&O stock ka 3:00–3:15 VWAP, final cash close aur front-month future close comparison.",
     "बाजार बंद होने के बाद F&O स्टॉक के 3:00–3:15 VWAP, अंतिम कैश क्लोज़ और फ्रंट-मंथ फ्यूचर क्लोज़ की तुलना।",
     "Select a stock and analyze after close. If official auction imbalance is absent from broker data, TPS labels the result as an estimate.",
     "Stock select karke close ke baad analyze karein. Official auction imbalance na mile to result estimate label hoga.",
     "स्टॉक चुनकर बंद होने के बाद विश्लेषण करें। आधिकारिक नीलामी असंतुलन न मिले तो परिणाम अनुमान के रूप में दिखेगा।"),
    (20, "Stock Options Watch",
     "Tracks selected liquid NSE F&O stocks and evaluates their cash, futures and option setup on completed candles.",
     "Selected liquid NSE F&O stocks ke cash, future aur option setup ko completed candles par track karta hai.",
     "चुने हुए तरल NSE F&O स्टॉक के कैश, फ्यूचर और ऑप्शन सेटअप को पूर्ण कैंडल पर ट्रैक करता है।",
     "Add/remove up to the configured watch limit, scan a stock and inspect CE/PE candidate, score, blockers, contract, entry, stop, target and quantity. Auto Radar may also discover candidates independently.",
     "Watch add/remove, scan aur CE/PE candidate, score, blocker, contract, entry, stop, target, quantity dekhein. Auto Radar independent discovery bhi karta hai.",
     "वॉच जोड़ें/हटाएँ, स्कैन करें और CE/PE उम्मीदवार, स्कोर, अवरोध, कॉन्ट्रैक्ट, एंट्री, स्टॉप, लक्ष्य, मात्रा देखें। Auto Radar स्वतंत्र खोज भी करता है।"),
    (21, "Option Strategies",
     "VIX/regime-aware defined-risk current-expiry research with live legs, target-profit reference, defined maximum loss, breakeven and estimated portfolio Greeks.",
     "VIX/regime-aware current-expiry research—live legs, target-profit reference, defined maximum loss, breakeven aur estimated portfolio Greeks.",
     "VIX/रेजीम आधारित सीमित-जोखिम रणनीति रिसर्च—लाइव लेग मूल्य, पेऑफ, ब्रेकईवन और अनुमानित पोर्टफोलियो ग्रीक्स।",
     "Analyze the smart defined-risk candidate and review Fibonacci as supporting context. Set an optional combined daily paper target and maximum loss: when either is reached, all open Strategy Trades close at their latest verified model mark and new captures lock for that date. Zero disables a limit. This is not a guaranteed result; always verify broker margin and quotes.",
     "Smart defined-risk candidate analyze karein aur Fibonacci ko supporting context samjhein. Optional combined daily paper target aur maximum loss set kar sakte hain. Koi limit hit hote hi sab open Strategy Trades latest verified model mark par close honge aur us date ke fresh captures lock ho jayenge. Zero ka matlab limit disabled hai. Profit guarantee nahi; broker margin/quote verify karein.",
     "स्मार्ट सीमित-जोखिम उम्मीदवार का विश्लेषण करें। वैकल्पिक संयुक्त दैनिक पेपर लक्ष्य और अधिकतम हानि तय करें। कोई सीमा पूरी होते ही सभी खुले Strategy Trades नवीनतम सत्यापित मॉडल मूल्य पर बंद होंगे और उस दिन नई कैप्चर बंद रहेंगी। शून्य का अर्थ सीमा बंद है। यह लाभ की गारंटी नहीं है।"),
    (22, "Post Market Analysis of TPS",
     "Automatic date-wise Roman-Hindi audit explaining why TPS captured or rejected trades and where monitoring/data gaps occurred.",
     "Date-wise automatic Roman-Hindi audit—TPS ne trade kyo capture/reject kiya aur monitoring/data gap kahan tha.",
     "तारीख़वार स्वचालित रोमन-हिंदी ऑडिट—TPS ने ट्रेड क्यों लिया/नहीं लिया और मॉनिटरिंग/डेटा अंतर कहाँ था।",
     "Select a date and refresh/generate. TPS creates reports after market close and backfills missed completed dates after restart.",
     "Date select karke refresh/generate karein. Market close ke baad report auto banti aur restart par missed date backfill hoti hai.",
     "तारीख चुनकर रीफ़्रेश/जनरेट करें। बाजार बंद होने के बाद रिपोर्ट स्वतः बनती और रीस्टार्ट पर छूटी तारीख भरती है।"),
    (23, "Pre-Candle Probability",
     "Experimental Candle-DNA model that compares completed patterns and publishes next-candle probabilities only after walk-forward validation.",
     "Experimental Candle-DNA model jo completed pattern compare karta aur walk-forward validation ke baad probability publish karta hai.",
     "प्रायोगिक Candle-DNA मॉडल जो पूर्ण पैटर्न तुलना करता और walk-forward सत्यापन के बाद अगली कैंडल संभावना प्रकाशित करता है।",
     "Choose symbol and purity gate (50–95), then analyze. Prediction is hidden until enough out-of-sample signals achieve required purity; 60% is not guaranteed future accuracy.",
     "Symbol/purity gate choose karein. Enough out-of-sample validation tak prediction hidden rahega; 60% future guarantee nahi.",
     "सिंबल/प्योरिटी सीमा चुनें। पर्याप्त out-of-sample सत्यापन तक पूर्वानुमान छिपा रहेगा; 60% भविष्य की गारंटी नहीं।"),
    (24, "Powerful Engine",
     "Selective confluence controller combining validated Candle DNA, 5m/15m/1h structure, EMA/VWAP/SuperTrend, price action, volume, VIX, OI and option liquidity.",
     "Validated Candle DNA, multi-timeframe structure, EMA/VWAP/SuperTrend, price action, volume, VIX, OI aur liquidity ka selective confluence controller.",
     "सत्यापित Candle DNA, बहु-टाइमफ्रेम संरचना, EMA/VWAP/SuperTrend, प्राइस एक्शन, वॉल्यूम, VIX, OI और लिक्विडिटी का चयनात्मक संगम नियंत्रक।",
     "Select index and analyze. It publishes CE/PE only when independent layers and liquidity gates agree; otherwise it deliberately returns WAIT with blockers.",
     "Index select karke Analyze karein. Independent layers agree hon tabhi CE/PE, warna blocker ke saath WAIT.",
     "इंडेक्स चुनकर Analyze करें। स्वतंत्र परतें सहमत हों तभी CE/PE, अन्यथा अवरोध सहित WAIT।"),
    (25, "Options Market Intelligence",
     "Nearest-expiry derivatives context: Call/Put OI, change in OI, PCR, strike walls, ATM expected move, focused Max Pain, IV/Greeks estimates and chain quality.",
     "Nearest-expiry context—Call/Put OI, change OI, PCR, strike walls, ATM expected move, focused Max Pain, IV/Greeks estimate aur chain quality.",
     "निकटतम एक्सपायरी संदर्भ—Call/Put OI, OI बदलाव, PCR, स्ट्राइक वॉल, ATM अपेक्षित चाल, focused Max Pain, IV/Greeks अनुमान और चेन गुणवत्ता।",
     "Choose index and Refresh Live OI/PCR; select strikes in the table. Expected move and Max Pain are expiry context, not standalone direction signals; limited quote windows are labelled focused.",
     "Index choose karke Refresh karein. Expected move/Max Pain expiry context hain, standalone direction nahi; limited window focused label hota hai.",
     "इंडेक्स चुनकर Refresh करें। Expected move/Max Pain एक्सपायरी संदर्भ हैं, अकेले दिशा संकेत नहीं; सीमित विंडो focused कहलाती है।"),
    (26, "3:20 + 3:40 Gap Probability",
     "Saves a separate 3:20 actionable forecast and 3:40 post-close confirmation for the next session from completed Spot/Future structure, basis, OI-PCR and optional published FII/DII data.",
     "Completed Spot/Future structure, basis, OI-PCR aur optional published FII/DII se separate 3:20 actionable aur 3:40 closing-confirmation probability save karta hai.",
     "पूर्ण स्पॉट/फ्यूचर संरचना, बेसिस, OI-PCR और वैकल्पिक प्रकाशित FII/DII से अगले सत्र की Gap Up/Flat/Gap Down संभावना सुरक्षित करता है।",
     "Keep TPS open with broker data connected: it auto-captures the selected index near 3:20 and recalculates at/after 3:40. Compare CONFIRMED/CHANGED, then verify both against next open. Manual overnight action remains risky.",
     "TPS open aur broker connected rakhein: selected index 3:20 ke paas auto-capture aur 3:40 ke baad recalculate hoga. CONFIRMED/CHANGED compare karein; overnight manual action risky rahega.",
     "3:20 के बाद चलाएँ, आधिकारिक फ्लो वैकल्पिक भरें, पूर्वानुमान सेव कर अगले ओपन से जाँचें। उसी दिन का अंतिम FII/DII अधूरा हो सकता है।"),
    (27, "Auto Opportunity Radar",
     "Unattended read-only scanner that discovers active NSE F&O stocks and checks index options, stock options and cash equities after completed 5-minute candles.",
     "Unattended read-only scanner jo active NSE F&O stocks discover karke completed 5-minute candle ke baad index option, stock option aur cash equity check karta hai.",
     "स्वचालित read-only स्कैनर जो सक्रिय NSE F&O स्टॉक खोजकर पूर्ण 5-मिनट कैंडल के बाद इंडेक्स ऑप्शन, स्टॉक ऑप्शन और कैश इक्विटी जाँचता है।",
     "Run Diagnostic Scan or let automatic cycles work; inspect action, instrument, score, entry, stop, targets, quantity, R:R, evidence and blockers. It never sends an order and may return zero candidates.",
     "Diagnostic Scan ya auto cycle use karein; action, instrument, score, entry, stop, targets, qty, R:R, evidence/blocker dekhein. Order kabhi nahi bhejta.",
     "Diagnostic Scan या ऑटो चक्र उपयोग करें; एक्शन, इंस्ट्रूमेंट, स्कोर, एंट्री, स्टॉप, लक्ष्य, मात्रा, R:R, प्रमाण/अवरोध देखें। यह ऑर्डर नहीं भेजता।"),
    (28, "Trend Memory Monitor",
     "Builds a permanent daily market-fingerprint database and compares the developing session with historically similar trend, chart-shape, Candle-DNA, indicator and OI contexts.",
     "Har din ka permanent market fingerprint save karke current session ko purane similar trend, chart shape, Candle DNA, indicator aur OI context se compare karta hai.",
     "Har din ka sthayi market fingerprint save karke vartaman session ki tulna purane saman trend, chart shape, Candle DNA, indicator aur OI sandarbh se karta hai.",
     "Choose an index and refresh. Saved days include actual outcomes; after six current 5-minute observations, an 80%+ analog can produce one desktop alert. Similarity is evidence, not a guaranteed forecast.",
     "Index choose karke refresh karein. Saved dates ke actual outcome dikhte hain; 6 current observations ke baad 80%+ analog par desktop alert aa sakta hai. Similarity forecast guarantee nahi hai.",
     "Index chun kar refresh karein. Chhah current observations ke baad 80% se adhik samanata par desktop alert aa sakta hai. Samanata bhavishyavani ki guarantee nahi hai."),
    (29, "Near-Expiry Options Scalper",
     "Selects the nearest-expiry ATM or one-step ITM/OTM CE/PE strike. Index-future candles supply direction and volume context, while the selected option's own completed premium candles control confirmation, entry, stop and targets.",
     "Nearest-expiry ATM ya one-step ITM/OTM CE/PE strike select karta hai. Index future sirf direction/volume context deta hai; selected option ki apni premium candles confirmation, entry, stop aur targets banati hain.",
     "निकटतम एक्सपायरी का ATM या एक-स्टेप ITM/OTM CE/PE स्ट्राइक चुनता है। इंडेक्स फ्यूचर केवल दिशा/वॉल्यूम संदर्भ देता है; चुने हुए ऑप्शन की प्रीमियम कैंडल पुष्टि, एंट्री, स्टॉप और लक्ष्य बनाती हैं।",
     "Choose index, strike mode and a 60-95 gate. Auto monitor checks every 20 seconds but evaluates completed future and option candles only. A watch needs direction plus selected-option EMA/VWAP/momentum/volume and quote-spread confirmation. No futures or options order is placed.",
     "Index, strike mode aur 60-95 gate choose karein. Alert ke liye direction ke saath selected-option EMA/VWAP/momentum/volume aur spread confirmation chahiye. Future ya option order place nahi hota.",
     "इंडेक्स, स्ट्राइक मोड और 60-95 सीमा चुनें। अलर्ट के लिए दिशा के साथ चुने हुए ऑप्शन की EMA/VWAP/मोमेंटम/वॉल्यूम और स्प्रेड पुष्टि जरूरी है। कोई ऑर्डर नहीं लगता।"),
    (30, "Notification Center",
     "Permanent date-and-time history of every desktop alert actually delivered by TPS, including its source category, title, complete message and read/unread state.",
     "TPS ke har delivered desktop alert ka permanent date-time record—source category, title, complete message aur read/unread status ke saath.",
     "TPS द्वारा दिए गए हर डेस्कटॉप अलर्ट का स्थायी दिनांक-समय रिकॉर्ड, जिसमें स्रोत श्रेणी, शीर्षक, पूरा संदेश और पढ़ा/अपठित स्थिति शामिल है।",
     "Use Today, All or Unread filters; select an alert for full detail, mark one/all as read, or export the current view to CSV. Disabled or duplicate-suppressed alerts are not recorded because they were not delivered.",
     "Today, All ya Unread filter use karein; alert select karke full detail padhein, selected/all ko read mark karein ya current view CSV me export karein. Disabled ya duplicate-suppressed popup delivered nahi hua, isliye record nahi hota.",
     "Today, All या Unread फ़िल्टर चुनें; पूरा विवरण पढ़ें, एक/सभी अलर्ट को पढ़ा हुआ चिह्नित करें या वर्तमान सूची CSV में निर्यात करें। बंद या डुप्लिकेट-दबा हुआ अलर्ट दिया नहीं गया, इसलिए दर्ज नहीं होता।"),
    (31, "AI Self-Development Decision Center",
     "Audits each completed post-market report and saves explainable software-health findings and evidence-led development rectification suggestions.",
     "Har completed post-market report ko audit karke software health aur evidence-based development rectification suggestions date-wise save karta hai.",
     "हर पूर्ण पोस्ट-मार्केट रिपोर्ट का ऑडिट करके सॉफ्टवेयर स्वास्थ्य और प्रमाण-आधारित सुधार सुझाव दिनांक के अनुसार सुरक्षित करता है।",
     "Select a saved date to inspect health, verdict, priority, observation, evidence, suggested development and its approval test. Mark suggestions Reviewed or reopen them. TPS never changes source code or strategy rules automatically.",
     "Saved date select karke health, verdict, priority, observation, evidence, suggested development aur approval test dekhein. Suggestion ko Reviewed ya Open mark kar sakte hain. TPS code/rules khud change nahi karta.",
     "सुरक्षित दिनांक चुनकर स्वास्थ्य, निर्णय, प्राथमिकता, अवलोकन, प्रमाण, विकास सुझाव और अनुमोदन परीक्षण देखें। सुझाव को Reviewed या Open करें। TPS स्वयं कोड या नियम नहीं बदलता।"),
    (32, "Overtrading Protection Center",
     "Behavioural safety and paper-validation center. Normal mode enforces check-in, paper-only commitment, bounded daily captures and consecutive-loss cooling. Temporary Testing Mode allows up to 20 simulated captures per day and measures targets, stops, time exits and accuracy.",
     "Behavioural safety aur paper-validation center. Normal mode check-in, paper-only commitment, daily limit aur loss cooling enforce karta hai. Temporary Testing Mode maximum 20 simulated captures/day allow karke target, stop, time-exit aur accuracy measure karta hai.",
     "व्यवहार सुरक्षा और पेपर-वैलिडेशन केंद्र। सामान्य मोड चेक-इन, पेपर-ओनली प्रतिबद्धता, दैनिक सीमा और लगातार हानि कूलिंग लागू करता है। अस्थायी Testing Mode प्रतिदिन अधिकतम 20 simulated captures की target, stop, time-exit और accuracy मापता है।",
     "Keep Testing Mode OFF for recovery/real-trade discipline. Turn it ON only for paper validation and choose a 1–20 limit. It bypasses behavioural frequency/cooling only; event, stale-data, liquidity, expiry, risk, one-open-position, target, stop-loss and time-exit safeguards remain active.",
     "Recovery ya real-trade discipline ke liye Testing Mode OFF rakhein. Sirf paper validation me ON karke 1–20 limit select karein. Ye behavioural frequency/cooling ko hi suspend karta hai; event, stale-data, liquidity, expiry, risk, one-open-position, target, stop-loss aur time-exit safety active rehti hai.",
     "Recovery या real-trade अनुशासन के लिए Testing Mode OFF रखें। केवल paper validation में ON करके 1–20 सीमा चुनें। Event, stale-data, liquidity, expiry, risk, एक खुली position, target, stop-loss और time-exit सुरक्षा सक्रिय रहती है।"),
    (33, "Volatility Intelligence",
     "Compares the India VIX implied daily move with actual completed-candle movement, ATR and realised volatility. It classifies volatility by the current VIX historical percentile and keeps movement potential separate from market direction.",
     "India VIX implied daily move ko completed-candle actual move, ATR aur realised volatility se compare karta hai. Current VIX ko historical percentile se Low/Normal/High/Extreme regime me rakhta hai; movement potential ko direction se alag rakhta hai.",
     "इंडिया VIX के अनुमानित दैनिक मूव की तुलना पूर्ण कैंडल के वास्तविक मूव, ATR और वास्तविक अस्थिरता से करता है। वर्तमान VIX को ऐतिहासिक परसेंटाइल से Low/Normal/High/Extreme श्रेणी में रखता है।",
     "Select NIFTY, BANKNIFTY or SENSEX and load live comparison. Review expected move, actual range, utilization, VIX trend/percentile, ATR, realised volatility, direction/volume strength, option-chain levels and defined-risk strategy context. Expected move is not a target or guaranteed boundary.",
     "Index select karke live comparison load karein. Expected move, actual range, utilization, VIX trend/percentile, ATR, realised volatility, direction-volume strength, OI levels aur defined-risk strategy context dekhein. Expected move target ya guarantee nahi hai.",
     "इंडेक्स चुनकर लाइव तुलना लोड करें। Expected move, actual range, utilization, VIX trend/percentile, ATR, realised volatility, दिशा-वॉल्यूम शक्ति, OI स्तर और defined-risk strategy context देखें। Expected move लक्ष्य या गारंटी नहीं है।"),
    (35, "Expiry After 3 PM Observation",
     "Research-only expiry-day monitor for nearby ATM and ITM index options after 3:00 PM. It records premium acceleration together with spot, volume, OI, option context, sustain time and CAS context; it is not a Buy/Sell signal.",
     "Expiry day par 3:00 PM ke baad nearby ATM/ITM index options ka research monitor. Premium acceleration ke saath spot, volume, OI, option context, sustain time aur CAS context save hota hai; yeh Buy/Sell signal nahi hai.",
     "एक्सपायरी दिन पर दोपहर 3 बजे के बाद निकट ATM/ITM इंडेक्स ऑप्शन का रिसर्च मॉनिटर। प्रीमियम तेज़ी के साथ स्पॉट, वॉल्यूम, OI, ऑप्शन संदर्भ, टिकाव समय और CAS संदर्भ सुरक्षित होता है; यह Buy/Sell संकेत नहीं है।",
     "Select the index and turn Today is Expiry ON only for the relevant expiry session. TPS verifies the actual nearest expiry and market window, polls every 30 seconds, and logs a Spike Event only when price acceleration has volume, OI-change or spot-breakout confirmation. Missing IV/Greeks remain clearly marked as a partial data source.",
     "Index select karke sirf relevant expiry session me Today is Expiry ON karein. TPS actual nearest expiry aur market window verify karke har 30 second observe karta hai. Price acceleration ko volume, OI-change ya spot-breakout confirmation mile tabhi Spike Event save hota hai. Missing IV/Greeks partial data source ke roop me clear rahenge.",
     "इंडेक्स चुनकर केवल संबंधित एक्सपायरी सत्र में Today is Expiry चालू करें। TPS वास्तविक निकटतम एक्सपायरी और बाजार समय जाँचकर हर 30 सेकंड अवलोकन करता है। मूल्य तेज़ी को वॉल्यूम, OI बदलाव या स्पॉट ब्रेकआउट पुष्टि मिलने पर ही Spike Event सुरक्षित होता है। उपलब्ध न होने वाले IV/Greeks को आंशिक डेटा के रूप में स्पष्ट दिखाया जाता है।"),
)

# Release 1.4 keeps these specialist tools but presents them as tabs inside
# their primary workflow.  Their historical route numbers intentionally stay
# valid so saved links continue to open the correct consolidated tab.
_CONSOLIDATED_TITLES = {
    5: "Session Checklist (Options Workspace)",
    11: "Raw Market Timeline (Post Market Analysis)",
    18: "Smart Money Evidence (Powerful Engine)",
    20: "Pinned F&O Watchlist (Auto Opportunity Radar)",
    23: "Candle DNA (Powerful Engine)",
    25: "OI / PCR Intelligence (Options Workspace)",
    33: "VIX / ATR Intelligence (Option Strategies)",
}
PAGES = tuple(
    (row[0], _CONSOLIDATED_TITLES.get(row[0], row[1]), *row[2:])
    for row in PAGES if row[0] not in {3, 7, 17}
)


def help_html(language: str) -> str:
    """Render one complete manual; language is en, roman or hi."""
    language_index = {"en": (2, 5), "roman": (3, 6), "hi": (4, 7)}[language]
    purpose_index, option_index = language_index
    headings = {
        "en": ("TPS Complete Page Guide", "Purpose", "Main options, output and caution", "Open this page", "Page index"),
        "roman": ("TPS Complete Page Guide — Roman Hindi", "Is page ka kaam", "Main options, output aur caution", "Ye page kholen", "Page list"),
        "hi": ("TPS संपूर्ण पेज मार्गदर्शिका", "इस पेज का कार्य", "मुख्य विकल्प, परिणाम और सावधानी", "यह पेज खोलें", "पेज सूची"),
    }[language]
    title, purpose_label, option_label, open_label, index_label = headings
    toc = " | ".join(f'<a href="#page-{row[0]}">{escape(row[1])}</a>' for row in PAGES)
    sections = []
    for row in PAGES:
        page_index, page_title = row[0], row[1]
        sections.append(
            f'<a name="page-{page_index}"></a><h2>{escape(page_title)}</h2>'
            f'<p><b>{escape(purpose_label)}:</b> {escape(row[purpose_index])}</p>'
            f'<p><b>{escape(option_label)}:</b> {escape(row[option_index])}</p>'
            f'<p><a href="tps://page/{page_index}">▶ {escape(open_label)} — {escape(page_title)}</a> &nbsp; '
            f'<a href="#top">↑ Top</a></p><hr>'
        )
    safety = {
        "en": "TPS is research, discipline and paper-validation software. Confluence, confidence, expected move, IV, PCR, Max Pain and probability are not guaranteed returns or financial advice. Verify live price, spread, liquidity, expiry, quantity, event risk and broker state before any manual action.",
        "roman": "TPS research, discipline aur paper-validation software hai. Confluence, confidence, expected move, IV, PCR, Max Pain ya probability guaranteed return/financial advice nahi. Manual action se pehle live price, spread, liquidity, expiry, quantity, event risk aur broker state verify karein.",
        "hi": "TPS रिसर्च, अनुशासन और पेपर-सत्यापन सॉफ्टवेयर है। Confluence, confidence, expected move, IV, PCR, Max Pain या probability सुनिश्चित रिटर्न/वित्तीय सलाह नहीं हैं। किसी मैनुअल कार्रवाई से पहले लाइव मूल्य, स्प्रेड, लिक्विडिटी, एक्सपायरी, मात्रा, इवेंट जोखिम और ब्रोकर स्थिति जाँचें।",
    }[language]
    return (
        f'<a name="top"></a><h1>{escape(title)}</h1>'
        f'<p><b>{escape(index_label)}:</b> {toc}</p>'
        f'<p class="safety"><b>Safety:</b> {escape(safety)}</p><hr>'
        + "".join(sections)
    )
