"""Application release metadata kept in one place."""

APP_NAME = "TPS AI Trading Assistant"
VERSION = "1.5.4"
DISPLAY_VERSION = "Release 1.5.4"
RELEASE_DATE = "03-09-2026"
PUBLISHER = "Tapas Kumar Pahar"

# Update this block whenever a reviewed application update is made.
SOFTWARE_UPDATE_VERSION = "v1.5.4"
LAST_UPDATED_AT = "03-09-2026 11:43:50 IST"
FOOTER_UPDATE_TEXT = "Software Update v1.5.4 - 03-09-2026 11:43 IST"
RELEASE_NOTES = (
    "Added an official NSE after-market import workflow in Reliability Cockpit: CM/FO UDiFF Bhavcopy ZIP or CSV files are hash-deduplicated, normalized and retained as BACKFILLED closing OHLC/volume/OI evidence without pretending to replace missing live intraday candles.",
    "Added explicit Market Data Hub watermarks LIVE, DELAYED, STALE and MISSING with active-request visibility; test/mock provider telemetry is now rejected before it can contaminate the production reliability database.",
    "Added Index Component Breadth: NIFTY, BANKNIFTY and SENSEX constituent quotes are captured in broker-rate-conscious batches every five minutes, with green/red/flat counts, 80% coverage protection and a 2-of-3 combined market verdict timestamped to the latest snapshot.",
    "Component breadth is retained as independent chart/OI confirmation rather than an automatic trade permission; incomplete constituent coverage is explicitly DATA GAP so a partial heat-map cannot manufacture bullish or bearish confidence.",
    "Extended the gap-qualified lifecycle to safeguarded REAL positions: target, stop, time exit, product type and expiry now survive restart; every action reconciles the broker entry fill and exact net position before monitoring or submitting an opposite-side exit.",
    "REAL overnight carry requires CARRYFORWARD, a non-expired contract, matching protected gap evidence and broker-confirmed quantity; the next open can tighten target/trailing protection from a fresh executable quote, while position mismatch, data gaps and uncertain exits fail closed without automatic duplicate retries.",
    "Added PAPER-only gap-supported overnight carry: a normal time exit may be deferred only when a protected saved next-session forecast matches CE/PE direction, clears confidence/data-quality/lead thresholds and the option remains valid beyond the target session.",
    "Overnight PAPER positions remain dormant outside regular trading, then require a fresh favourable executable option quote at the next open; TPS modestly adjusts the target, raises a non-loosening trailing stop to protect the observed move, or records an Overnight Gap Exit when confirmation fails.",
    "Expanded Auto Attempts into a page-level scrolling audit view: the attempt ledger now keeps ten rows visible with independent horizontal and vertical scrolling, while complete selected-attempt evidence remains available below it.",
    "Strengthened support/resistance evidence: chart levels remain repeated completed-candle swing zones, while option-chain walls are now concentrated multi-strike OI zones with peak share and STRONG/USABLE/DISTRIBUTED quality instead of a moving single maximum strike.",
    "Zero-OI or poor-coverage option chains can no longer manufacture support/resistance; unreliable OI proximity is a soft observation/data gap and cannot become a hard entry wall without usable chain quality.",
    "Added automatic three-index Auto Paper monitoring: every eligible completed 5-minute cycle evaluates NIFTY, BANKNIFTY and SENSEX sequentially in the background without depending on the manually selected Options Workspace index.",
    "Separated Auto Attempt reporting into ALL, NIFTY, BANKNIFTY and SENSEX tabs with per-index attempts, captured/open/closed samples, measured closed-trade win rate, Wilson confidence lower bound, expectancy and validation state.",
    "A 70% accuracy goal is now treated as a measured validation target rather than a promise: fewer than 30 closed samples remain LOW SAMPLE/LEARNING, and score bands never masquerade as probability.",
    "Added Smart Options Memory: every saved completed 5-minute index-future candle is paired with candlestick anatomy, futures-volume participation and nearby option OI/COI flow, then compared with prior-day analogs and their actual next-candle outcomes.",
    "Added Angel One Order Intelligence: read-only live order-book monitoring, current move/MFE/MAE evidence, explainable hold/protect-profit/exit-risk review states and persistent post-trade snapshots without automatic broker action.",
    "Added Release 1.5.3 reliability controls: fresh-data hard gating, one-blocker candle replay, score-band outcome calibration, correlated strategy portfolio exposure, and consistent attempt-versus-slot reporting.",
    "Separated broker transport success from usable market freshness and added stale-response ratio plus p50/p95 latency evidence to the Reliability Cockpit.",
    "Added a Reliability Cockpit with a saved trade-decision timeline, missed-opportunity replay shortlist, regime-wise strategy performance matrix, execution-quality evidence and statistically gated shadow-mode eligibility.",
    "Added a common REAL execution data-quality gate: market session, broker connection, shared snapshot freshness and provider health must be valid, and REAL review remains paper-only until 30 outcomes, positive expectancy, profit factor and confidence gates pass.",
    "Broker reconciliation now persists average fill, filled quantity and adverse limit-to-fill slippage; missing fill evidence stays DATA GAP instead of being estimated.",
    "Added Ctrl+K Quick Open for direct keyboard access to TPS pages and a Dashboard shortcut to the complete reliability audit.",
    "Added an original expiry 3 PM shadow-research score combining premium acceleration, volume participation, OI change, spot direction and source completeness; it remains paper/shadow evidence and does not copy or assume undisclosed video rules.",
    "Replaced the long scrolling sidebar with five compact workspace groups; every existing TPS page is now one-click accessible through visible Market, Trading, Reports or Controls tabs while legacy Help routes and automatic navigation remain compatible.",
    "Added Angel One official publisher login with a local security-state callback, secure broker-issued session storage and read-only funds verification; direct MPIN/TOTP login remains a fallback.",
    "Added a canonical Market Data Hub, unique paper-thesis sampling, executable bid/ask paper fills, net-of-friction outcomes, dashboard health controls and conservative strategy ranking for the Release 1.5.2 reliability upgrade.",
    "Reworked Options Workspace PAPER Testing Mode into exploratory forward validation: up to 10 independent trades/day may be monitored concurrently, so one running simulation no longer blocks the next completed-candle sample.",
    "Exploratory capture may tolerate at most two soft checklist misses and a bounded score relaxation, but still requires directional consensus, directional volume, complete data, liquid contract selection, risk-sized quantity and zero hard blockers.",
    "Each exploratory plan permanently records its validation track, relaxed score floor and soft-miss count; every trade keeps its own target, adaptive stop-loss, trailing/time exit and outcome so daily accuracy remains measurable.",
    "Added a central bounded analysis scheduler: at most three heavy jobs run together, duplicate active work is dropped, and high-frequency page timers start at stable staggered offsets instead of colliding.",
    "Moved three-index candle/OI analysis completely off the UI thread, added incremental unchanged-table suppression, and exposed live scheduler activity, completed runs, saved duplicates and slowest-job timing on Dashboard.",
    "Added shared same-day in-memory instrument/contract parsing plus SQLite WAL, normal synchronization and busy-timeout settings so background writes no longer unnecessarily block UI report reads.",
    "Added Expiry ATM Premium Parity entry: after 3 PM on the actual expiry day, the closest ATM same-strike CE and PE can be captured as one paired intent when their premiums differ by no more than ₹10.",
    "Parity entry uses one quote-batch observation timestamp for both legs, records the exact premium gap and blocks repeat entry for the same dated index/strike even after restart; REAL submission still requires existing session authorization and both-leg preflight.",
    "Broker APIs cannot guarantee identical exchange fill timestamps for two orders; TPS therefore validates both legs before submission and cancels/unwinds a partial pair if one leg fails or rejects.",
    "Added an official NSE equity/F&O trading-day calendar and a central live-alert firewall: weekends, published exchange holidays and closed sessions can no longer produce fresh opportunity, scalp, OI, structure, early-watch or strategy suggestions from stale candles.",
    "Stopped closed-session background polling in Auto Opportunity Radar, Options Scalper and Index Market Analysis while retaining exactly one final index refresh, target/stop/exit safety monitoring, 3:40 closing confirmation and post-market report generation.",
    "Made the Index Market Analysis evidence table content-aware: compact columns auto-size, the full explanation keeps a readable bounded width, rows expand for wrapped text, and smooth horizontal/vertical scrollbars appear whenever the screen cannot show all evidence.",
    "Added Live Index Intelligence & After Market Analysis: NIFTY, BANKNIFTY and SENSEX are automatically evaluated on every completed five-minute index-future candle with price anatomy, traded volume, near-ATM OI/COI flow, buyer/seller aggression, cross-index breadth and permanent evidence explanations.",
    "Added automatic date-wise index conclusion reports with explicit source-completeness and FII/DII data-gap labels; SENSEX closing-auction observations are identified as CAS/settlement repricing instead of being misreported as ordinary continuous cash candles.",
    "Added chart-first Candle Anatomy and Chart + OI Confluence: completed-candle displacement, body/wicks, repeated rejection, volume participation and fresh OI-flow alignment now produce an evidence-timed explanation without claiming unknowable participant intent.",
    "Added a review-only OI-flow strike shortlist to Options Market Intelligence with ATM/slightly-ITM liquidity preference, TRUE/FALSE/UNKNOWN evidence, entry zone, premium/spot invalidation references, two targets and a safer defined-risk vertical alternative.",
    "Added OI Flow Intelligence inside Options Market Intelligence: legacy OI PCR is separated from fresh absolute COI flow, unreliable small-base COI percentages are suppressed, dynamic CE/PE wall health is labelled, and near-money strike coverage adapts between 5 and 7 wings.",
    "OI Flow combines exchange-reported COI, premium-change quadrant, volume participation, ATM proximity and source coverage into BULLISH/BEARISH/BALANCED context; it reports DATA GAP warnings and never turns OI alone into entry permission.",
    "Added one-time daily REAL Pilot authorization: a single Cutie command or Broker Execution button arms the bounded session, after which structured orders may use automatic preflight without repeating a phrase for every order; all pilot caps, mandatory exits, broker, market, data and duplicate locks remain enforced.",
    "Added opt-in Limited REAL Pilot Mode: arming requires the pilot switch, every submitted entry requires target and stop values, and code-level ceilings enforce at most two accepted entries/day, quantity 65, 0.25% planned risk/trade and 0.5% recorded daily loss regardless of larger UI values.",
    "Cutie REAL prompts now route to Broker Execution for exact contract and final session review; they never auto-submit, and no unlimited-authority switch is provided.",
    "Expanded Cutie AI Command Center into Cutie AI Assistant: natural Hindi/English navigation can open TPS workspaces such as Dashboard, Settings, Strategy Trades and Expiry After 3 PM, while trading commands remain separated from ordinary software actions.",
    "Added Cutie AI Command Center with guarded Hindi/English prompts for PAPER algo start, status and kill switch; prompts compile into allow-listed typed intents and cannot bypass market, data, liquidity, event, risk, daily-loss, broker or emergency-stop controls.",
    "REAL automation prompts fail closed until broker fill reconciliation plus managed target/stop/time exits are certified end to end; an AI prompt never directly submits an unrestricted broker order.",
    "Moved the live read-only broker balance from Broker Execution to a dedicated Dashboard Broker Funds card; it refreshes after connection, whenever Dashboard opens, on Refresh Dashboard and every 60 seconds with an IST freshness timestamp.",
    "Made Broker Account Funds self-refreshing: balance loads immediately after broker connection and whenever the execution page opens, then refreshes every 60 seconds without blocking the interface; every successful value shows its IST update time and failed responses are marked non-current.",
    "Started Release 1.5.1 Capital Guardian: new installations default to 0.25% per-trade and 0.5% daily loss budgets while existing saved user settings remain preserved across upgrades.",
    "Replaced the fixed option-premium stop with an adaptive volatility/liquidity stop: minimum breathing room, regime adjustment, bid/ask-spread allowance and a bounded wick/sweep buffer are recorded as evidence.",
    "A wider adaptive stop now reduces whole-lot quantity; when even one exchange lot cannot fit the configured rupee-risk cap, TPS skips the plan instead of manufacturing a dangerously tight stop.",
    "Added cost-aware Options Algo deployment readiness: configurable entry window, estimated slippage, net expectancy, profit factor, maximum drawdown and minimum paper-evidence gates are now visible before any real-order review; PAPER observation remains available and these metrics never authorize a broker order.",
    "Added a dedicated Options Algo Trading Control Center with saved daily net-profit, maximum-loss, estimated-charge, lot and 1-10 trade boundaries; PAPER entries use the existing completed-candle evidence engine and new entries stop automatically at any daily boundary.",
    "Kept the options-algo activation session-only, continued target/stop/time-exit monitoring after its new-entry kill switch, and fail-closed REAL automation until broker fill reconciliation plus managed exits are verified end to end.",
    "Started Release 1.5.0 with PAPER as the safe default order mode, saved amount/percentage/exact-price target and stop settings, optional time-exit planning and read-only Angel One account-funds visibility.",
    "Added an audited Paper Order Plan path that never contacts the broker; REAL entry remains LIMIT-only and requires saved opt-in, an app-session unlock, market hours, risk caps, duplicate protection and final review.",
    "Expanded Expiry After 3 PM Observation with same-strike paired CE/PE evidence: both premiums are saved at the rolling start, spike event and latest follow-up so the rising side and opposite-side decline can be studied together.",
    "Added Expiry After 3 PM Observation: an opt-in, research-only expiry-day monitor for nearby ATM and ITM index-option premium acceleration after 3:00 PM.",
    "Added permanent 30-second observation and Spike Event history with spot, premium change, incremental-volume surge, OI change, ATM distance, optional IV/Greeks, sustain duration and source-completeness evidence.",
    "Made expiry spike confirmation context-aware: price acceleration alone remains PRICE WATCH; a saved spike also requires volume, OI-change or underlying-breakout confirmation, while cash-market CAS is labelled as context and never misread as an index-option halt.",
    "Added a saved daily combined target-profit and maximum-loss guard on Option Strategies; when either paper limit is reached, all open Strategy Trades close at their latest verified model P&L and further captures lock for that trading date.",
    "Added live daily Strategy Trades P&L, target, loss-limit and guard-state visibility while preserving the 30-strategy testing cap and keeping this workflow paper-only with no broker orders or guaranteed profit.",
    "Added individual Strategy Trade reports: every closed multi-leg paper strategy now has its own STR report, detail view and date/period Excel export instead of being visible only inside aggregate counts.",
    "Connected defined-risk Strategy Trades to Post Market Analysis with separate closed/open/win/loss counts, realized model P&L, individual outcome lines and a warning for unreconciled open simulations.",
    "Added market-close strategy reconciliation so remaining open paper strategies are closed from their last verified saved mark and a missing date-wise session review is backfilled without placing a broker order.",
    "Restored the Strategy Trades live comparison board with up to 30 current-market defined-risk candidates ranked by model score, market fit, scenario-positive coverage and payoff evidence; actual win rate remains a separate closed-paper metric.",
    "Expanded paper validation to retain eligible counterfactual strategy candidates alongside primary market-aligned candidates, while keeping unbounded or risk-ineligible structures comparison-only.",
    "Made release packaging stamp the footer from the computer's actual local build time so Software Update time is no longer manually guessed or confused with the live clock.",
    "Fixed the Strategy Trades capture pipeline to consume the portfolio engine's canonical market-alignment evidence; eligible aligned multi-leg strategies now persist to the ledger and ranking instead of disappearing after analysis.",
    "Moved Strategy Trades out of the Option Strategies tab container into a genuinely independent sidebar page; Defined-Risk and VIX/ATR analysis remain together while captured multi-leg performance has its own clean workspace.",
    "Recovered Option Strategies from provider hangs and unexpected broker-SDK errors with a 90-second watchdog, generation-safe late-result rejection and automatic next-cycle retry; Strategy Trades now resumes receiving successful upstream analyses instead of remaining blank indefinitely.",
    "Separated Strategy Trades from Option Strategies: live Defined-Risk and VIX/ATR analysis stays on Option Strategies, while Strategy Trades now shows only captured trades, saved capture/scenario scores and outcomes.",
    "Rebuilt the Strategy Trades leaderboard to rank actual closed paper results by win rate first, then sample count and total P&L, with the top-ranked strategy shown first.",
    "Added Strategy Trades: an automatic multi-leg defined-risk paper ledger connected to live Option Strategies analysis and the Trade Journal.",
    "Added ten strategy comparisons covering directional spreads, credit spreads, iron structures, butterflies and volatility structures; only fully bounded payoff candidates are auto-captured.",
    "Expanded Strategy Trades to compare up to 30 strike combinations with friendly Cutie names, estimated defined-risk fund, entry cashflow, model ROC and market-regime outcome grouping.",
    "Added executable bid/ask mark-to-market, automatic benefit/loss-review/time exits, permanent outcome explanations and a forward-validation leaderboard by strategy.",
    "Added a 30-unique-strategy-trades-per-day testing cap and candle/structure deduplication; no broker order is placed and no profit is guaranteed.",
    "Added an AI Development Center Implementation & Benefit Report that links every saved suggestion to its verified build/release, lifecycle evidence, measured replay or paper-forward benefit, pending reason and explicit next-release action.",
    "Preserved each feature's original implementation provenance across later refreshes and prevented code presence alone from being reported as a proven benefit.",
    "Removed redundant manual Chart Capture, standalone Risk Calculator and snapshot-based Next-Day Bias screens from the primary workflow; legacy links now open their automatic replacements.",
    "Started Release 1.4.5 with TPS expanded visibly as Trading Plan System in the application header.",
    "Added automatic closed-trade outcome memory: target, stop-loss, trailing-stop and time-exit results now receive a permanent Cutie postmortem and corrective solution without manual journal entry.",
    "Added condition fingerprints and duplicate-safe historical trade analog alerts so a newly captured setup can reference a similar past trade and its actual outcome as context, never as a profit guarantee.",
    "Upgraded Option Strategies with a smart READY/WATCH/DATA-GAP suggestion flow so a near-valid fully hedged structure is explained instead of disappearing behind a generic WAIT.",
    "Added completed-candle Fibonacci swing and 23.6/38.2/50/61.8/78.6 retracement context as supporting evidence; it never bypasses liquidity, expiry, risk, event or late-session locks.",
    "Added a read-only what-if gate simulator comparing the saved score/checklist with balanced and exploratory paper-study gates without changing production settings or weakening hard safety blockers.",
    "Added an evidence-led late-entry guard after the 24 August stop-loss audit: a fresh-trigger grace entry is now rejected when it is already beyond the preferred ATR extension and the VIX-implied daily movement budget is exhausted.",
    "Added expected-range utilization, remaining movement points and movement-state evidence beside entry timing in Options Workspace and the permanent Auto Attempt report; normal fresh-trigger grace remains available while movement budget exists.",
    "Rebuilt the Overtrading Protection page inside a dedicated vertical scroll area with protected section heights, mouse-wheel movement and visible arrow controls so testing-mode, guard, validation and recovery fields no longer overlap on shorter displays.",
    "Made paper target, stop-loss and configured time exits independent of the Options page lifecycle with an always-on 10-second watchdog; one failed contract quote no longer pauses monitoring of other open paper trades.",
    "Added a last-verified-premium fallback for mandatory paper time exits when the broker returns an error or blank quote, with a resolved audit record instead of a lingering active alert.",
    "Added an explicit temporary Paper Validation Testing Mode with a configurable 1-20 simulated-trade daily limit while keeping event, data-quality, liquidity, expiry, risk, one-open-position, target, stop-loss and time-exit safeguards active.",
    "Expanded paper self-validation with captured, open and closed counts, target/stop/time-exit outcomes, target-versus-stop accuracy and closed-trade P&L win rate.",
    "Made Angel One instrument discovery resilient with verified last-known-good fallback, three bounded live retries, response validation and atomic cache replacement so a temporary master-download outage does not erase an otherwise evaluable market window.",
    "Corrected Auto Attempt classification: EARLY WATCH and low-score CE/PE observations are now STRATEGY REJECT, while CANDIDATE is reserved for a fully qualified strategy; proven legacy WATCH mislabels are repaired without changing genuine trade history.",
    "Added Cutie as the friendly user-facing guidance voice while retaining TPS AI Trading Assistant as the software brand.",
    "Expanded saved-plan monitoring with Strategy Health and DO NOTHING, WATCH TREND CHANGE, PREPARE HEDGE ADJUSTMENT, BOOK PAPER TARGET, CUT RISK and EXIT & SWITCH SIDE decisions.",
    "Opposite-side replacements now display their expiry, paper target reference and defined maximum loss after the existing structure's close-first sequence.",
    "Upgraded Option Strategies with explicit current-expiry candidate side, conservative paper target-profit reference, loss-review threshold and unchanged defined maximum loss.",
    "Added confirmed CE-to-PE and PE-to-CE thesis transitions: TPS closes the saved defined-risk structure first and only then presents an optional fresh opposite-side replacement.",
    "Added target/loss-reference monitoring from conservative executable bid/ask quotes while retaining manual review, risk-cap, expiry, liquidity and no-naked-option safeguards.",
    "Corrected zero-capture over-blocking: a single-touch/fallback swing level is now an auditable warning instead of a support/resistance hard wall that follows every falling or rising candle.",
    "Repeated clustered chart zones and option-chain OI walls remain strict proximity blockers, alongside fake-breakout, late-entry, RSI, event, liquidity, daily-loss and recovery safeguards.",
    "Added regime-aware directional-volume confirmation for established TRENDING continuation when structure, VWAP, EMA 5/20/50, candle direction and at least normal Volume-EMA participation all agree.",
    "Trend Memory now classifies the complete session using EMA/VWAP persistence ratios so a late bounce cannot relabel a persistent downtrend as RANGE / MIXED.",
    "Added regression coverage for falling-market fallback support, repeated reliable support, trend-continuation volume and full-session bearish Trend Memory classification.",
    "Added editable Pre-open, Regular Trading Start and Market Close times in Settings; countdowns, candle monitoring, daily evaluation coverage and fresh-entry safety now use the saved session.",
    "Explained Early Watch in Settings and Help as an optional near-qualified completed-candle study alert, never a trade or entry approval.",
    "Made all tab bars theme-aware with readable selected, unselected and hover colours across every TPS colour and UI-style combination.",
    "Rebuilt Market Snapshot support/resistance as clustered completed-candle swing zones and retained a valid zone until invalidation or a replacement repeats across three analyses.",
    "Stopped Market Snapshot index cross-talk and flashing by discarding stale analysis responses and live ticks that do not belong to the currently selected NIFTY, BANKNIFTY or SENSEX token.",
    "Added Release 1.4.1 evidence integrity: every strategy fact is TRUE, FALSE or UNKNOWN, and UNKNOWN is reported as a DATA GAP instead of silently becoming a pass or rejection.",
    "Standardized Auto Attempt outcomes as DATA GAP, SAFETY BLOCK, STRATEGY REJECT, CANDIDATE and CAPTURED with primary blocker, deduplicated secondary warnings and source-completeness evidence.",
    "Upgraded counterfactual validation to relax exactly one strategy blocker at a time while retaining every news, broker, stale-data, daily-loss, cooldown and recovery safety lock.",
    "Counterfactual replay now measures MFE, MAE, target-before-stop, stop-before-target, false-entry outcome and maximum drawdown from later saved candles without look-ahead.",
    "Replaced hard-coded AI Development implementation labels with persisted feature version, build ID and evidence-backed Suggested/Implemented/Replay/Paper Forward/Approved lifecycle states.",
    "Added DRAFT/FINAL AI reviews, revision history, source fingerprinting and automatic new DRAFT revisions when post-market evidence changes.",
    "Added explicit evaluation coverage numerator/denominator and COMPLETE/PARTIAL/NO EVIDENCE watermark.",
    "Strengthened Trend Memory with minimum completed-session coverage, snapshot-quality-weighted similarity and a permanent context-only rule that cannot permit or block a trade.",
    "Preserved no-look-ahead signal discovery, first-valid-trigger, final-capture and timing-delay evidence for late-entry and MFE studies.",
    "Added a compact gear shortcut beside the live header clock so Settings opens directly while the sidebar selection remains synchronized.",
    "Consolidated eight overlapping standalone workspaces into six primary tabbed hubs while preserving their calculations, saved data and legacy Help routes.",
    "Options Workspace now contains Trade Plan & Auto Paper plus OI / PCR Intelligence tabs; the standalone Checklist route now opens its persistent Session Checklist.",
    "Powerful Engine now groups Combined Signal, Smart Money Evidence and Candle DNA so the combined decision and its specialist evidence can be reviewed together.",
    "Auto Opportunity Radar now includes Automatic Opportunities and an optional Pinned F&O Watchlist tab without requiring a separate watchlist page.",
    "Post Market Analysis of TPS now includes the automatic daily Roman-Hindi analysis and the raw saved market timeline in one workspace.",
    "3:20 + 3:40 Gap Probability now includes the Closing Bias / Snapshot Fallback workflow as a second tab.",
    "Option Strategies now includes a VIX / ATR Intelligence tab for expected-move, realised-range and volatility-regime evidence.",
    "Removed duplicate sidebar entries without deleting their specialist tools; old Help links safely redirect to the matching consolidated tab.",
    "Moved the testing trade-plan score and all news/event safety controls from contract selection into one Session Checklist section with a complete save receipt.",
    "Protected Required Matches, Match Rule, event window and testing score from accidental mouse-wheel changes while the Options Workspace page scrolls.",
    "Removed the disconnected manual Decision Engine V1 / AI Analysis workspace; verified Chart Capture values now evaluate directly and continue to Options Workspace without an extra duplicate form.",
    "Added an immediate inline save confirmation with date, time, selected-evidence count, match rule and required matches to the Options Workspace session checklist.",
    "Added an opt-in Regular 20-Point Scalp paper-validation mode to Options Workspace with separate index-point and option-premium objectives, configurable evidence thresholds, READY/WATCH/NO TRADE classification and permanent five-minute attempt audit.",
    "Regular scalp validation cannot capture or place an order and cannot bypass strict TPS hard blockers, nearby chart/OI levels, stale entry timing, directional-volume evidence or exhausted VIX/ATR movement budget.",
    "Added a dedicated Volatility Intelligence workspace comparing India VIX implied daily move with actual session movement, ATR and realised volatility.",
    "Replaced fixed-only VIX labels with a one-year historical percentile regime when sufficient broker history is available, while clearly retaining the older absolute fallback when history is unavailable.",
    "Added expected-range utilization, remaining movement budget, VIX rising/falling context and one shared volatility source for Market Snapshot and defined-risk Option Strategies.",
    "Corrected the AI Development Center at 1080p by adding a dedicated wheel-and-arrow page scroll area, protected working height and non-overlapping suggestion and evidence panels.",
    "Published Release 1.3.1 with simplified supported-broker onboarding and VIX/ATM-range-aware defined-risk strategy adjustment monitoring.",
    "Simplified supported-broker onboarding with an official setup/login button and clear one-time secure setup guidance; broker API authentication remains mandatory.",
    "Enhanced Option Strategies with India-VIX/ATM-range-aware defined-risk strike selection and a save-and-monitor adjustment workflow.",
    "Added completed-5-minute HOLD, WATCH and EXIT/REASSESS monitoring with exact close-leg actions, optional fresh defined-risk replacement and a strict no-naked-option rule.",
    "Completed Release 1.3 evidence validation with persistent five-minute heartbeat, missed-slot backfill and explicit gap reason codes.",
    "Added broker reliability telemetry, data-age tracking and last-good request evidence for auto-paper diagnostics.",
    "Added safe counterfactual score/confirmation replay that never changes production settings or bypasses hard blockers.",
    "Added volume reason classification, chart/OI level confluence, ATR distance, level age and paper outcome MAE/MFE evidence.",
    "Added a Release 1.3 validation dashboard with separate implementation and live-evidence approval states.",
    "Added a complete Excel Report Center with one-day, inclusive date-range and all-available filters plus a multi-sheet All TPS Reports workbook.",
    "Added styled XLSX exports for Trade Journal, Auto Attempts, Notifications, Auto Opportunities, Market Snapshots, PCR/OI, Gap Probability, Trend Memory, Post Market Analysis and AI Self-Development records.",
    "Added direct date/period Excel export controls to the main audit and analysis report pages while retaining existing CSV exports.",
    "Added no-look-ahead signal timing telemetry with separate discovery, first-valid trigger and final paper-capture timestamps plus measured delay.",
    "Added an opt-in Early Watch paper-observation notification for near-qualified completed candles; it is disabled by default and never bypasses final strategy or safety approval.",
    "Expanded Auto Attempt Report and CSV export with timing stage, timing milestones and delay evidence for replay validation against false entries.",
    "Started Release 1.3 with a dedicated Overtrading Protection Center and a persistent daily emotional-safety check-in.",
    "Enabled Recovery Mode by default: one new paper capture per day, a 48-hour cooling lock after two consecutive paper losses, and a 30-session paper-validation target.",
    "Applied the central recovery guard to both automatic and manual paper captures so strategy scores and signals cannot override behavioural safety locks.",
    "Kept market observation, reports and historical evidence available while captures are paused; TPS still has no broker-order placement endpoint.",
    "Corrected installed-app startup placement so Release 1.2.2 opens maximized inside the current monitor work area with the native title bar, TPS header and footer visible.",
    "Published maintenance Release 1.2.2 with aligned application, Windows executable, installer, portable ZIP and checksum metadata.",
    "Made Trend Memory similarity alerts restart-safe and limited each logical current-day/historical-day match to one delivered notification per day.",
    "Stopped repeated Support/Resistance and Auto Opportunity popup floods with restart-safe daily event identities instead of changing live-price message text.",
    "Added Notification Center cleanup for historic repeated alerts while retaining the first daily event record.",
    "Added AI Self-Development Decision Center with permanent date-wise system health, evidence-led rectification suggestions, priority and Open/Reviewed workflow.",
    "Daily reviews audit monitoring coverage, broker retries, zero-capture calibration, entry timing, volume and level evidence, overtrading and target/stop outcomes without silently changing code or strategy rules.",
    "Added a permanent Notification Center that records every delivered TPS desktop alert with local date/time, source category, title, full message and read/unread state.",
    "Added Today, All and Unread notification views, unread sidebar count, selected-alert detail, mark-read controls and CSV export; notification history survives restarts and installer updates.",
    "Corrected SENSEX auto-paper confirmation so sparse current-month-future volume samples are shown as unavailable evidence instead of an automatic directional-volume failure.",
    "Kept EMA alignment and SuperTrend relevant in low-volatility sessions, reduced the accidental all-checks requirement, and added a bounded 25% fresh-trigger grace band before entry extension becomes a hard late-entry veto.",
    "Separated entry-quality warnings from genuine hard safety blockers; fake-breakout risk, extreme RSI, nearby unbroken support/resistance and materially chased entries remain protected.",
    "Redesigned Scalper Command Center as a nearest-expiry options scalper: actual watch instrument is an ATM/one-step ITM/OTM CE or PE strike, never an index-future trade.",
    "Future candles now provide direction and traded-volume context only; the selected option's completed premium candles independently validate EMA/VWAP, momentum, volume and spread before publication.",
    "Moved scalp Entry, SL, T1 and T2 to the selected option premium using ask/LTP and option-premium ATR, with exact contract, strike mode and expiry shown in the UI and notification.",
    "Added TPS Scalper Command Center with completed 1-minute triggers, 5-minute direction, EMA/VWAP, momentum, futures-volume expansion, adaptive confluence threshold and duplicate-safe desktop watches.",
    "Added official NSE IX GIFT Nifty context plus clearly labelled external US/Asia reference breadth; global movement is a bounded confirmation layer and cannot override Indian completed-candle direction.",
    "Added explainable scalp entry reference, ATR protection, two targets and a complete PASS/WAIT evidence ledger while retaining read-only, notification-only safety.",
    "Added Trend Memory Monitor with a permanent daily market-fingerprint database for trend, chart shape, Candle DNA, EMA/VWAP/SuperTrend, volume, RSI/ATR and OI-PCR context.",
    "Added live historical analog matching and an optional desktop alert when the developing session reaches 80% similarity with a completed saved market day, including that day's actual outcome.",
    "Published maintenance Release 1.2.1 with aligned application, Windows executable, installer, portable ZIP and Help Center version metadata.",
    "Expanded Gap Probability Lab into separate 3:20 actionable and 3:40 post-close confirmation forecasts shown together with CONFIRMED/CHANGED comparison.",
    "Added automatic selected-index capture near 3:20 PM and retry-safe closing recalculation at/after 3:40 PM when TPS is open and broker data is connected.",
    "Protected closing confirmation from weekends, stale broker candles and rapid repeated API retries; both stages remain independently auditable against the next market open.",
    "Made Help Center text, headings, links, safety notes and separators automatically follow every colour theme and UI design style with high-contrast reader colours.",
    "Help pages now refresh immediately during theme preview without requiring an application restart, while preserving the current reading position.",
    "Rebuilt Help Center as a complete 28-page offline manual in English, Roman Hindi and Hindi, with purpose, main controls, outputs and cautions for every workspace.",
    "Added route-aware Help links: clicking Open this page now jumps directly to the referenced TPS workspace and updates the active sidebar item.",
    "Upgraded Put-Call Ratio into Options Market Intelligence with ATM straddle expected move/range, focused-window Max Pain, bid/ask spread coverage, chain data-quality score and transparent context labels.",
    "Added live-premium Black-Scholes ATM IV/Greeks estimates when expiry inputs are safe, while clearly withholding estimates when data is incomplete.",
    "Added estimated whole-position Delta, Gamma, Theta and Vega to valid limited-risk option strategies, plus expected-move, Max-Pain and chain-quality evidence in strategy and automatic opportunity reports.",
    "Auto Opportunity Radar now discovers its own liquid, active candidates from the complete NSE F&O stock universe; a manual watchlist is no longer required.",
    "Added a rate-conscious two-stage scan: lightweight universe ranking by turnover, movement and intraday participation, followed by deep TPS candle, futures and option-chain validation only for the strongest shortlist.",
    "Added TPS Auto Opportunity Radar: an unattended completed-5-minute-candle scanner for NIFTY, BANKNIFTY, SENSEX, configured stock-option watches and Equity Research watchlists.",
    "Added a permanent opportunity audit with BUY/WAIT/ERROR state, instrument, entry, protective exit, two targets, quantity, R:R, score, evidence and rejection reasons.",
    "The radar reuses Powerful Engine and existing TPS/OI/liquidity gates, runs automatically after broker connection and every eligible five-minute cycle, and remains research/paper-only without broker order placement.",
    "Added a separate 3:20 Gap Probability Lab for NIFTY, BANKNIFTY and SENSEX with Gap Up, Flat and Gap Down probabilities.",
    "Combined completed Spot/Future trend, futures basis, OI-PCR and optional latest-published official FII/FPI and DII cash flow without inventing unavailable values.",
    "Added permanent forecast history and automatic next-session open verification so TPS can show measured sample accuracy instead of claiming guaranteed prediction.",
    "Protected saved settings across source updates, new builds and installer upgrades with AppData migration, atomic writes and automatic backup recovery.",
    "Added support/resistance proximity alerts when live price enters or crosses the chart levels marked by TPS.",
    "Added a Put-Call Ratio & OI Observer for Call OI, Put OI, change in OI, OI-PCR, Volume-PCR, OI walls and explainable sentiment context.",
    "Added a central Windows desktop Notification Center with a global switch, sound control and page/event-wise alert controls.",
    "Added desktop alerts for paper-trade capture, exit, target, stop loss, Open Trade Guard, market-structure changes and completed post-market reports.",
    "Added TPS Powerful Engine, a selective CE/PE signal controller combining Candle DNA purity, 5m/15m/1h structure, EMA/VWAP/SuperTrend, price action, volume, VIX, OI and ATM liquidity.",
    "Powerful Engine abstains on conflicting, missing, unvalidated or illiquid evidence and keeps confluence strength separate from historically measured prediction purity.",
    "Added the experimental Pre-Candle Probability Lab with Candle DNA analog matching, bullish/bearish/range probabilities and a configurable 50-95% publication gate.",
    "Added expanding walk-forward purity validation so a next-candle signal is hidden until at least 15 eligible out-of-sample historical predictions clear the selected purity threshold.",
    "Added an official read-only Paytm Money adapter with browser authorization, secure token storage, instrument mapping, quotes, candles, OI and live-price support.",
    "Made Dhan authentication rate-safe so market-data permission failures no longer trigger a second token within two minutes, and inactive Data API plans are explained clearly.",
    "Added a complete read-only Dhan adapter with automatic daily access-token renewal, instrument mapping, candles, quotes, OI and live price updates.",
    "Added CAS Analysis and Stock Options Watch workspaces.",
    "Added adaptive market-regime rules and limited-risk Option Strategies.",
    "Refined Market Snapshot cards so values remain separated and readable.",
    "Added reliable mouse-wheel scrolling and visible scrollbar arrow controls.",
    "Made 'No known high-impact event' the default Options Workspace event status.",
    "Added visible software-update metadata and dated Help Center release notes.",
    "Added permanent date-wise Roman Hindi 'Post Market Analysis of TPS' journal.",
    "Made TPS post-market reports generate automatically after market close with restart backfill.",
)
