"""Application release metadata kept in one place."""

APP_NAME = "TPS AI Trading Assistant"
VERSION = "1.4"
DISPLAY_VERSION = "Release 1.4"
RELEASE_DATE = "14-08-2026"
PUBLISHER = "Tapas Kumar Pahar"

# Update this block whenever a reviewed application update is made.
SOFTWARE_UPDATE_VERSION = "v1.4"
LAST_UPDATED_AT = "17-08-2026 08:45:34 IST"
FOOTER_UPDATE_TEXT = "Software Update v1.4 - 17-08-2026 08:45 IST"
RELEASE_NOTES = (
    "Added a compact gear shortcut beside the live header clock so Settings opens directly while the sidebar selection remains synchronized.",
    "Consolidated eight overlapping standalone workspaces into six primary tabbed hubs while preserving their calculations, saved data and legacy Help routes.",
    "Options Workspace now contains Trade Plan & Auto Paper plus OI / PCR Intelligence tabs; the standalone Checklist route now opens its persistent Session Checklist.",
    "Powerful Engine now groups Combined Signal, Smart Money Evidence and Candle DNA so the combined decision and its specialist evidence can be reviewed together.",
    "Auto Opportunity Radar now includes Automatic Opportunities and an optional Pinned F&O Watchlist tab without requiring a separate watchlist page.",
    "Post Market Analysis of TPS now includes the automatic daily Roman-Hindi analysis and the raw saved market timeline in one workspace.",
    "3:20 + 3:40 Gap Probability now includes the Closing Bias / Snapshot Fallback workflow as a second tab.",
    "Option Strategies now includes a VIX / ATR Intelligence tab for expected-move, realised-range and volatility-regime evidence.",
    "Removed duplicate sidebar entries without deleting their specialist tools; old Help links safely redirect to the matching consolidated tab.",
    "Moved the testing trade-plan score and all news/event safety controls from contract selection into one Session Checklist section with a complete save receipt.",
    "Protected Required Matches, Match Rule, event window and testing score from accidental mouse-wheel changes while the Options Workspace page scrolls.",
    "Removed the disconnected manual Decision Engine V1 / AI Analysis workspace; verified Chart Capture values now evaluate directly and continue to Options Workspace without an extra duplicate form.",
    "Added an immediate inline save confirmation with date, time, selected-evidence count, match rule and required matches to the Options Workspace session checklist.",
    "Added an opt-in Regular 20-Point Scalp paper-validation mode to Options Workspace with separate index-point and option-premium objectives, configurable evidence thresholds, READY/WATCH/NO TRADE classification and permanent five-minute attempt audit.",
    "Regular scalp validation cannot capture or place an order and cannot bypass strict TPS hard blockers, nearby chart/OI levels, stale entry timing, directional-volume evidence or exhausted VIX/ATR movement budget.",
    "Added a dedicated Volatility Intelligence workspace comparing India VIX implied daily move with actual session movement, ATR and realised volatility.",
    "Replaced fixed-only VIX labels with a one-year historical percentile regime when sufficient broker history is available, while clearly retaining the older absolute fallback when history is unavailable.",
    "Added expected-range utilization, remaining movement budget, VIX rising/falling context and one shared volatility source for Market Snapshot and defined-risk Option Strategies.",
    "Corrected the AI Development Center at 1080p by adding a dedicated wheel-and-arrow page scroll area, protected working height and non-overlapping suggestion and evidence panels.",
    "Published Release 1.3.1 with simplified supported-broker onboarding and VIX/ATM-range-aware defined-risk strategy adjustment monitoring.",
    "Simplified supported-broker onboarding with an official setup/login button and clear one-time secure setup guidance; broker API authentication remains mandatory.",
    "Enhanced Option Strategies with India-VIX/ATM-range-aware defined-risk strike selection and a save-and-monitor adjustment workflow.",
    "Added completed-5-minute HOLD, WATCH and EXIT/REASSESS monitoring with exact close-leg actions, optional fresh defined-risk replacement and a strict no-naked-option rule.",
    "Completed Release 1.3 evidence validation with persistent five-minute heartbeat, missed-slot backfill and explicit gap reason codes.",
    "Added broker reliability telemetry, data-age tracking and last-good request evidence for auto-paper diagnostics.",
    "Added safe counterfactual score/confirmation replay that never changes production settings or bypasses hard blockers.",
    "Added volume reason classification, chart/OI level confluence, ATR distance, level age and paper outcome MAE/MFE evidence.",
    "Added a Release 1.3 validation dashboard with separate implementation and live-evidence approval states.",
    "Added a complete Excel Report Center with one-day, inclusive date-range and all-available filters plus a multi-sheet All TPS Reports workbook.",
    "Added styled XLSX exports for Trade Journal, Auto Attempts, Notifications, Auto Opportunities, Market Snapshots, PCR/OI, Gap Probability, Trend Memory, Post Market Analysis and AI Self-Development records.",
    "Added direct date/period Excel export controls to the main audit and analysis report pages while retaining existing CSV exports.",
    "Added no-look-ahead signal timing telemetry with separate discovery, first-valid trigger and final paper-capture timestamps plus measured delay.",
    "Added an opt-in Early Watch paper-observation notification for near-qualified completed candles; it is disabled by default and never bypasses final strategy or safety approval.",
    "Expanded Auto Attempt Report and CSV export with timing stage, timing milestones and delay evidence for replay validation against false entries.",
    "Started Release 1.3 with a dedicated Overtrading Protection Center and a persistent daily emotional-safety check-in.",
    "Enabled Recovery Mode by default: one new paper capture per day, a 48-hour cooling lock after two consecutive paper losses, and a 30-session paper-validation target.",
    "Applied the central recovery guard to both automatic and manual paper captures so strategy scores and signals cannot override behavioural safety locks.",
    "Kept market observation, reports and historical evidence available while captures are paused; TPS still has no broker-order placement endpoint.",
    "Corrected installed-app startup placement so Release 1.2.2 opens maximized inside the current monitor work area with the native title bar, TPS header and footer visible.",
    "Published maintenance Release 1.2.2 with aligned application, Windows executable, installer, portable ZIP and checksum metadata.",
    "Made Trend Memory similarity alerts restart-safe and limited each logical current-day/historical-day match to one delivered notification per day.",
    "Stopped repeated Support/Resistance and Auto Opportunity popup floods with restart-safe daily event identities instead of changing live-price message text.",
    "Added Notification Center cleanup for historic repeated alerts while retaining the first daily event record.",
    "Added AI Self-Development Decision Center with permanent date-wise system health, evidence-led rectification suggestions, priority and Open/Reviewed workflow.",
    "Daily reviews audit monitoring coverage, broker retries, zero-capture calibration, entry timing, volume and level evidence, overtrading and target/stop outcomes without silently changing code or strategy rules.",
    "Added a permanent Notification Center that records every delivered TPS desktop alert with local date/time, source category, title, full message and read/unread state.",
    "Added Today, All and Unread notification views, unread sidebar count, selected-alert detail, mark-read controls and CSV export; notification history survives restarts and installer updates.",
    "Corrected SENSEX auto-paper confirmation so sparse current-month-future volume samples are shown as unavailable evidence instead of an automatic directional-volume failure.",
    "Kept EMA alignment and SuperTrend relevant in low-volatility sessions, reduced the accidental all-checks requirement, and added a bounded 25% fresh-trigger grace band before entry extension becomes a hard late-entry veto.",
    "Separated entry-quality warnings from genuine hard safety blockers; fake-breakout risk, extreme RSI, nearby unbroken support/resistance and materially chased entries remain protected.",
    "Redesigned Scalper Command Center as a nearest-expiry options scalper: actual watch instrument is an ATM/one-step ITM/OTM CE or PE strike, never an index-future trade.",
    "Future candles now provide direction and traded-volume context only; the selected option's completed premium candles independently validate EMA/VWAP, momentum, volume and spread before publication.",
    "Moved scalp Entry, SL, T1 and T2 to the selected option premium using ask/LTP and option-premium ATR, with exact contract, strike mode and expiry shown in the UI and notification.",
    "Added TPS Scalper Command Center with completed 1-minute triggers, 5-minute direction, EMA/VWAP, momentum, futures-volume expansion, adaptive confluence threshold and duplicate-safe desktop watches.",
    "Added official NSE IX GIFT Nifty context plus clearly labelled external US/Asia reference breadth; global movement is a bounded confirmation layer and cannot override Indian completed-candle direction.",
    "Added explainable scalp entry reference, ATR protection, two targets and a complete PASS/WAIT evidence ledger while retaining read-only, notification-only safety.",
    "Added Trend Memory Monitor with a permanent daily market-fingerprint database for trend, chart shape, Candle DNA, EMA/VWAP/SuperTrend, volume, RSI/ATR and OI-PCR context.",
    "Added live historical analog matching and an optional desktop alert when the developing session reaches 80% similarity with a completed saved market day, including that day's actual outcome.",
    "Published maintenance Release 1.2.1 with aligned application, Windows executable, installer, portable ZIP and Help Center version metadata.",
    "Expanded Gap Probability Lab into separate 3:20 actionable and 3:40 post-close confirmation forecasts shown together with CONFIRMED/CHANGED comparison.",
    "Added automatic selected-index capture near 3:20 PM and retry-safe closing recalculation at/after 3:40 PM when TPS is open and broker data is connected.",
    "Protected closing confirmation from weekends, stale broker candles and rapid repeated API retries; both stages remain independently auditable against the next market open.",
    "Made Help Center text, headings, links, safety notes and separators automatically follow every colour theme and UI design style with high-contrast reader colours.",
    "Help pages now refresh immediately during theme preview without requiring an application restart, while preserving the current reading position.",
    "Rebuilt Help Center as a complete 28-page offline manual in English, Roman Hindi and Hindi, with purpose, main controls, outputs and cautions for every workspace.",
    "Added route-aware Help links: clicking Open this page now jumps directly to the referenced TPS workspace and updates the active sidebar item.",
    "Upgraded Put-Call Ratio into Options Market Intelligence with ATM straddle expected move/range, focused-window Max Pain, bid/ask spread coverage, chain data-quality score and transparent context labels.",
    "Added live-premium Black-Scholes ATM IV/Greeks estimates when expiry inputs are safe, while clearly withholding estimates when data is incomplete.",
    "Added estimated whole-position Delta, Gamma, Theta and Vega to valid limited-risk option strategies, plus expected-move, Max-Pain and chain-quality evidence in strategy and automatic opportunity reports.",
    "Auto Opportunity Radar now discovers its own liquid, active candidates from the complete NSE F&O stock universe; a manual watchlist is no longer required.",
    "Added a rate-conscious two-stage scan: lightweight universe ranking by turnover, movement and intraday participation, followed by deep TPS candle, futures and option-chain validation only for the strongest shortlist.",
    "Added TPS Auto Opportunity Radar: an unattended completed-5-minute-candle scanner for NIFTY, BANKNIFTY, SENSEX, configured stock-option watches and Equity Research watchlists.",
    "Added a permanent opportunity audit with BUY/WAIT/ERROR state, instrument, entry, protective exit, two targets, quantity, R:R, score, evidence and rejection reasons.",
    "The radar reuses Powerful Engine and existing TPS/OI/liquidity gates, runs automatically after broker connection and every eligible five-minute cycle, and remains research/paper-only without broker order placement.",
    "Added a separate 3:20 Gap Probability Lab for NIFTY, BANKNIFTY and SENSEX with Gap Up, Flat and Gap Down probabilities.",
    "Combined completed Spot/Future trend, futures basis, OI-PCR and optional latest-published official FII/FPI and DII cash flow without inventing unavailable values.",
    "Added permanent forecast history and automatic next-session open verification so TPS can show measured sample accuracy instead of claiming guaranteed prediction.",
    "Protected saved settings across source updates, new builds and installer upgrades with AppData migration, atomic writes and automatic backup recovery.",
    "Added support/resistance proximity alerts when live price enters or crosses the chart levels marked by TPS.",
    "Added a Put-Call Ratio & OI Observer for Call OI, Put OI, change in OI, OI-PCR, Volume-PCR, OI walls and explainable sentiment context.",
    "Added a central Windows desktop Notification Center with a global switch, sound control and page/event-wise alert controls.",
    "Added desktop alerts for paper-trade capture, exit, target, stop loss, Open Trade Guard, market-structure changes and completed post-market reports.",
    "Added TPS Powerful Engine, a selective CE/PE signal controller combining Candle DNA purity, 5m/15m/1h structure, EMA/VWAP/SuperTrend, price action, volume, VIX, OI and ATM liquidity.",
    "Powerful Engine abstains on conflicting, missing, unvalidated or illiquid evidence and keeps confluence strength separate from historically measured prediction purity.",
    "Added the experimental Pre-Candle Probability Lab with Candle DNA analog matching, bullish/bearish/range probabilities and a configurable 50-95% publication gate.",
    "Added expanding walk-forward purity validation so a next-candle signal is hidden until at least 15 eligible out-of-sample historical predictions clear the selected purity threshold.",
    "Added an official read-only Paytm Money adapter with browser authorization, secure token storage, instrument mapping, quotes, candles, OI and live-price support.",
    "Made Dhan authentication rate-safe so market-data permission failures no longer trigger a second token within two minutes, and inactive Data API plans are explained clearly.",
    "Added a complete read-only Dhan adapter with automatic daily access-token renewal, instrument mapping, candles, quotes, OI and live price updates.",
    "Added CAS Analysis and Stock Options Watch workspaces.",
    "Added adaptive market-regime rules and limited-risk Option Strategies.",
    "Refined Market Snapshot cards so values remain separated and readable.",
    "Added reliable mouse-wheel scrolling and visible scrollbar arrow controls.",
    "Made 'No known high-impact event' the default Options Workspace event status.",
    "Added visible software-update metadata and dated Help Center release notes.",
    "Added permanent date-wise Roman Hindi 'Post Market Analysis of TPS' journal.",
    "Made TPS post-market reports generate automatically after market close with restart backfill.",
)

